name: Fly Deploy - production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: vars
        name: Compute short SHA for SENTRY_RELEASE
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Build static assets
        run: |
          npm clean-install 
          npm run build
      - name: Checkout repository with archived sites of previous years
        uses: actions/checkout@v3
        with:
          repository: pyvec/cz.pycon.org-2019
          path: _previous-years
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c fly.prod.toml --remote-only --build-arg SENTRY_RELEASE=${{ steps.vars.outputs.sha_short }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
